### PR TITLE
Support Firebase hosting

### PR DESCRIPTION
**Pull request by nicogarcia**
### Briefing
Adds support for firebase hosting.

#### To create a Firebase project
1. Go to console.firebase.google.com
2. Create project with name <project-name> (that will be the project subdomain, eg. vim-cheat-sheet.firebaseapp.com)

#### To deploy
1. Install firebase cli: `npm i -g firebase-cli`
2. cd into project folder
3. Select firebse project with `firebase use --add vim-cheat-sheet`
4. Run `yarn run deploy:firebase`

### Firebase Hosting

Free features:
  - Static hosting (with generous quota)
  - Custom domain
  - and many more

I've already deployed it temporarily here: https://vim-cs.firebaseapp.com/

Hope it helps :slightly_smiling_face:

### CODE REVIEW

**Comment by yann-yinn** [comment]
@nicogarcia Hello ! thanks for the PR :)
You mean you still have issues with https://vim-cheat-sheet.now.sh/ ?  :-/

it works just fine for me , so i would like to be sure there are other persons that have issues with "zeit now" hosting before changing domain name. Or find a way to reproduce your issue.

**Comment by nicogarcia** [comment]
No problem! I've just checked and it's still not working I get `ERR_CONNECTION_CLOSED`. Maybe it's just me :)

**Comment by yann-yinn** [comment]
@nicogarcia  strange ! 
are you connecting to http**S**://vim-cheat-sheet.now.sh/ (httpS and not http) ?
can you give me a screenshot or logs, your version of chrome, something to understand why you have this issue ? you are connecting from Argentina right?
I checked with proxies from several part of the world and it worked every time, so i have no clue for now

**Comment by yann-yinn** [comment]
@nicogarcia and can you try with another browser to be sure ?

**Comment by nicogarcia** [comment]
You're right 👍 Sorry, it's my computer (has some restrictions and I forgot about them), tried in the mobile phone and it's working 😬

**Comment by yann-yinn** [comment]
@nicogarcia glad to hear that :)

**Pull request closed without merging**
